### ISSUE TITLE
speech separation evaluator returns negative sdr sar

### ISSUE THREAD

**Issue by hemengyu0410** [avivga/cocktail-party#2]
Hello, thanks for your work!
I'm learning to evaluate my separated signals. My reference signal is original voice of single target speaker, estimated signal is the voice of the target speaker after the two speakers are separated. Both of them are .wav files. But mir_eval library returns negative SDR SAR. Is there something wrong about my input or anything else?
Looking forward for your reply

**Comment by avivga** [comment]
SDR and SAR are expressed in decibels (logarithmic scale) and therefore can be negative. Please see [this paper](https://hal.inria.fr/inria-00544230/document) for more details.
